services:
  web:
    container_name: propstgonz-web
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.propstgonz.rule=Host(`propstgonz.baronette.es`)"
      - "traefik.http.routers.propstgonz.entrypoints=websecure"
      - "traefik.http.routers.propstgonz.tls=true"
      - "traefik.http.services.propstgonz.loadbalancer.server.port=4321"

networks:
  traefik-net:
    external: true