version: '3.8'

services:
  astro:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install && npm run build && npx serve ./dist"
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    depends_on:
      - astro
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./dist:/usr/share/nginx/html:ro